In [1]:
import numpy as np

In [2]:
arr =np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [5]:
a = [1,2,3.5]
a  

[1, 2, 3.5]

In [6]:
np.array(a)

array([1. , 2. , 3.5])

In [7]:
l = [1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]
l

([1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15])

In [8]:
np.array(l)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [11]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [12]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
arr = np.linspace(1,5,2)
arr

array([1., 5.])

In [15]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [16]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [17]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [18]:
np.random.rand(5)

array([0.06166807, 0.04983538, 0.28699891, 0.08910083, 0.67558605])

In [20]:
np.random.rand(10)

array([0.28163557, 0.25867209, 0.94220945, 0.93824735, 0.86254738,
       0.49172709, 0.7505735 , 0.3601309 , 0.61624559, 0.37761509])

In [22]:
np.random.randn(10)

array([ 1.45939999e+00,  8.62408157e-01, -1.29902429e-01,  1.48397659e+00,
       -1.39812212e+00, -1.43225372e-04,  1.17439333e+00, -1.18516608e-01,
        8.87545684e-01,  2.36604218e+00])

In [23]:
np.random.randint(5)

4

In [24]:
np.random.randint(10,20,10)

array([12, 13, 14, 14, 18, 12, 19, 19, 19, 14])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.shape

(3, 3)

In [27]:
arr.size

9

In [28]:
arr.dtype

dtype('int64')

In [29]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr.min()

np.int64(1)

In [31]:
arr.max()

np.int64(9)

In [32]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [33]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [34]:
arr.min()

np.int64(1)

In [35]:
arr.mean()

np.float64(5.0)

In [36]:
arr.std()

np.float64(2.581988897471611)

In [37]:
arr.argmax()

np.int64(8)

In [38]:
arr.argmin()

np.int64(0)

In [39]:
arr =np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [40]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [41]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [42]:
arr(6)

TypeError: 'numpy.ndarray' object is not callable

In [43]:
arr[6]

np.int64(17)

In [44]:
arr[9]

np.int64(20)

In [45]:
arr[1:4]

array([12, 13, 14])

In [46]:
arr[1:5]

array([12, 13, 14, 15])

In [47]:
arr[0:5]

array([11, 12, 13, 14, 15])

In [48]:
arr[1:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [51]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [52]:
arr[4]

np.int64(15)

In [53]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [54]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [55]:
arr[5]

array([26, 27, 28, 29, 30])

In [56]:
arr[0,0]

np.int64(1)

In [57]:
arr[0,4]

np.int64(5)

In [58]:
arr[5,4]

np.int64(30)

In [59]:
slice_arr = arr[0:2, 1:3]
slice_arr

array([[2, 3],
       [7, 8]])

In [62]:
arr_slice = arr[3:, 3:]
arr_slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [63]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [3]:
import numpy as np

In [4]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [6]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [7]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a2

array([4, 5, 6])

In [8]:
a1 + a2

array([5, 7, 9])

In [9]:
a1*a2

array([ 4, 10, 18])

In [10]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [11]:
a1 // a2

array([0, 0, 0])

In [12]:
a1 - a2

array([-3, -3, -3])

In [13]:
a1 ** a2

array([  1,  32, 729])

In [14]:
l = [10, 20, 30, 40, 50]
arr = np.array(l)

In [15]:
arr + 10

array([20, 30, 40, 50, 60])

In [ ]:
a2 = np.arange(1,26).reshape(5,5)
